vim.opt.updatetime = 50
vim.opt.swapfile = false
vim.opt.relativenumber=true
vim.opt.nu=true
vim.opt.tabstop=4
vim.opt.softtabstop=4
vim.opt.shiftwidth=4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap=false
vim.opt.splitbelow=true
vim.opt.splitright=true
vim.opt.colorcolumn="120"
vim.opt.scrolloff=12
vim.opt.incsearch=true
vim.opt.ruler=true
vim.opt.hlsearch=true
vim.opt.expandtab=true
vim.opt.belloff=all
vim.opt.foldmethod="indent"
vim.opt.foldopen=block
vim.opt.foldlevel=99
vim.opt.encoding="utf-8"
vim.opt.signcolumn="yes"
vim.opt.backspace=[[indent,eol,start]]
vim.opt.hidden=true
vim.opt.undofile=true
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.completeopt=[[menu,menuone,noselect]]
vim.opt.termguicolors = true
